### ISSUE TITLE
Create a Sample Dataset of Shark Images Pulled From Youtube

### ISSUE THREAD

**Issue by kathirvelgounder** [squadledge/SharkSpotting#1]
- Taking a aerial video of a shark from youtube, splitting into a few frames, and then annotating it. 
- Find the right data organization for prebuilt Torch Faster-RCNN

**Comment by kathirvelgounder** [comment]
https://scalabel.ai/

Berkeley DeepDrives annotation tool

**Comment by xdhmoore** [comment]
Near the bottom of Kurfess' README there is a link to a Google Drive folder with a bunch of video footage. I'm not sure about the the Spring CSU data, but Fall CSU data is all videos.

**Comment by kathirvelgounder** [comment]
Closing this Issue since we have enough sample data from previous groups for testing
